### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by mvlkbcse** [jongchyisu/mvcnn_pytorch#10]
Hello,

I am trying to run the code on a different dataset. I have prepared the dataset and extracted the images correctly. But while training, I get the error 

```
Traceback (most recent call last):
  File "train_mvcnn.py", line 61, in <module>
    trainer.train(10)
  File "/home/bharadwajmanda/mvcnn_pytorch/tools/Trainer.py", line 65, in train
    self.writer.add_scalar('train/train_loss', loss, i_acc+i+1)
  File "/home/bharadwajmanda/anaconda3/envs/mvcnn/lib/python3.6/site-packages/tensorboardX/writer.py", line 341, in add_scalar
    scalar(tag, scalar_value), global_step, walltime)
  File "/home/bharadwajmanda/anaconda3/envs/mvcnn/lib/python3.6/site-packages/tensorboardX/summary.py", line 88, in scalar
    scalar = make_np(scalar)
  File "/home/bharadwajmanda/anaconda3/envs/mvcnn/lib/python3.6/site-packages/tensorboardX/x2num.py", line 27, in make_np
    return check_nan(prepare_pytorch(x))
  File "/home/bharadwajmanda/anaconda3/envs/mvcnn/lib/python3.6/site-packages/tensorboardX/x2num.py", line 40, in prepare_pytorch
    x = x.cpu().numpy()
RuntimeError: CUDA error: device-side assert triggered

```
Can you please help me with this?

Thanks,
Bharadwaj

**Comment by lukasdrescher1** [comment]
(How) Did you fix this?

**Comment by Echo-babe** [comment]
> Hello,
> 
> I am trying to run the code on a different dataset. I have prepared the dataset and extracted the images correctly. But while training, I get the error
> 
> ```
> Traceback (most recent call last):
>   File "train_mvcnn.py", line 61, in <module>
>     trainer.train(10)
>   File "/home/bharadwajmanda/mvcnn_pytorch/tools/Trainer.py", line 65, in train
>     self.writer.add_scalar('train/train_loss', loss, i_acc+i+1)
>   File "/home/bharadwajmanda/anaconda3/envs/mvcnn/lib/python3.6/site-packages/tensorboardX/writer.py", line 341, in add_scalar
>     scalar(tag, scalar_value), global_step, walltime)
>   File "/home/bharadwajmanda/anaconda3/envs/mvcnn/lib/python3.6/site-packages/tensorboardX/summary.py", line 88, in scalar
>     scalar = make_np(scalar)
>   File "/home/bharadwajmanda/anaconda3/envs/mvcnn/lib/python3.6/site-packages/tensorboardX/x2num.py", line 27, in make_np
>     return check_nan(prepare_pytorch(x))
>   File "/home/bharadwajmanda/anaconda3/envs/mvcnn/lib/python3.6/site-packages/tensorboardX/x2num.py", line 40, in prepare_pytorch
>     x = x.cpu().numpy()
> RuntimeError: CUDA error: device-side assert triggered
> ```
> 
> Can you please help me with this?
> 
> Thanks, Bharadwaj

Hello, I also encountered this problem, how did you solve it?
