### ISSUE TITLE
What are  -num_models -num_views parameters exactly

### ISSUE THREAD

**Issue by DilaraAlbayrak** [jongchyisu/mvcnn_pytorch#13]
In the command for given dataset num_models is 1000 and num_views is 12.

There is also a line which is
`n_models_train = args.num_models*args.num_views`

In this settings, n_models_train is 12000, but there are 118116 images in the train set.

I have a dataset in which there are 15 classes (1 instance per class) and there are 720 images per class. In sum, training set contains 10800 images in which 20 different views are represented. In that case, what should be my num_models parameter (I guess num_view parameter should be 20)?

**Comment by DilaraAlb** [comment]
Probably, i set some parameter incorrect, that is why i get below error after some epochs

`epoch 30, step 169: train_loss 0.001; train_acc 1.000
Total # of test models:  2100
val mean class acc. :  nan
val overall acc. :  0.75333333
val loss :  0.9212250899184834
Warning: NaN or Inf found in input tensor.
WARNING: summary folder already exists!! It will be overwritten!!
Traceback (most recent call last):
  File "train_mvcnn.py", line 73, in <module>
    train_dataset = MultiviewImgDataset(args.train_path, scale_aug=False, rot_aug=False, num_models=n_models_train, num_views=args.num_views)
  File "mvcnn_pytorch-master/tools/ImgDataset.py", line 36, in __init__
    all_files = all_files[::stride]
ValueError: slice step cannot be zero
`

**Comment by jongchyisu** [comment]
It's the number of models and number of views. I guess in your case it's 720*15 and 20 respectively.
