### ISSUE TITLE
The problem of dataset

### ISSUE THREAD

**Issue by RainbowSun1102** [jongchyisu/mvcnn_pytorch#15]
Hi, thank you for your code and work.

I compare the dataset you provided and the dataset provided by RotationNet (http://maxwell.cs.umass.edu/mvcnn-data/?C=D;O=A). These two datasets are the same. But RotationNet said this is a subset of ModelNet40. Is it right?

Thank you for your time and attention.

Rainbow

**Comment by jongchyisu** [comment]
The original mvcnn paper only uses a subset, while my mvcnn uses the whole modelnet40.

**Comment by RainbowSun1102** [comment]
Thank you for your reply. Do you mean the shaded images are the whole modelnet40?

Thank you for your time

**Comment by jongchyisu** [comment]
The on I provided is the whole modelnet40.
