### ISSUE TITLE
why I am getting ValueError: num_samples should be a positive integeral value, but got num_samples=0

### ISSUE THREAD

**Issue by garimss** [jongchyisu/mvcnn_pytorch#16]
D:\git_hub\mvcnn_pytorch>python train_mvcnn.py -name mvcnn -num_models 1000 -weight_decay 0.001 -num_views 12 -cnn_name vgg11
WARNING: summary folder already exists!! It will be overwritten!!
WARNING: summary folder already exists!! It will be overwritten!!
Downloading: "https://download.pytorch.org/models/vgg11-bbd30ac9.pth" to C:\Users\Garima/.torch\models\vgg11-bbd30ac9.pth
531456000it [05:07, 1731015.24it/s]
Traceback (most recent call last):
  File "train_mvcnn.py", line 54, in <module>
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True, num_workers=0)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\torch\utils\data\dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "C:\Users\Garima\Anaconda3\envs\fastai-3.7\lib\site-packages\torch\utils\data\sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0

**Comment by y6216886** [comment]
Remember to put train data into the demanded path
