### ISSUE TITLE
multi_view dataset construction

### ISSUE THREAD

**Issue by jonathanbonnard** [jongchyisu/mvcnn_pytorch#20]
Hi,
I have a small remark about the way the python file ImgDataset.py:MultiviewImgDataset(torch.utils.data.Dataset) is constructing the multi_view batch images. In fact, when you use stride = int(12/self.num_views), the trainer has only access to the same poses of an object. 
For example, if you use self.num_views = 2, the trainer always get something like :
(car.XXX.001.png and car.XXX.007.png) 
or 
(cup.XXX.001.png and cup.XXX.007.png)

and this is the same problem for num_views = 3, 4, 6

I think this might be a big issue because there is no randomness in the multi view training stage.
If you validate the system with different poses, how the CNN could get the same performance?

**Comment by jongchyisu** [comment]
This is actually intentional. We want the same set of viewpoints for training. Otherwise, if you randomly sample the views you are using all 12 views. Also note that we are not using the aligned modelnet dataset.
