### ISSUE TITLE
blender script for help

### ISSUE THREAD

**Issue by wd-hub** [jongchyisu/mvcnn_pytorch#6]
HI Jong-Chyi,
I'm very interested in your work and trying to use your blender script to generate rendered views. But I find that Blender Script for shaded and depth images are exactly the same. Is there something wrong?

And in the Blender Script, it converts the *.off model to *.obj model by using the off2obj, is it an additional python script that used? I tried to find the convert script by google and used airplane_0627.off as an example for rendering, but the result is rather weird, it is
![airplane obj_whiteshaded_v0](https://user-images.githubusercontent.com/14939607/53421045-e4df2980-3a17-11e9-99a0-ab68034bf140.png)

By the way, how to use the Blender Script effectively? I'm really a newbie about blender and I'd appreciate it if you could you show me an example ;). 

Thanks very much.

**Comment by jongchyisu** [comment]
The files should be different, see the node editor part.
For off2obj, I use this https://www.antiprism.com/programs/off2obj.html but you can use any program to convert to format.

**Comment by wd-hub** [comment]
Thanks for your information, it works now!
It seems that the rendered Depth Images (1.5GB) given in the github is not complete. I downloaded twice but only got 29 classes objects from the zip archive every time.

**Comment by jongchyisu** [comment]
Thanks for letting me know that file was corrupted. I have updated the depth file.
