### ISSUE TITLE
same content in two Blender scripts

### ISSUE THREAD

**Issue by Luoyayu** [jongchyisu/mvcnn_pytorch#7]
`[Blender script for rendering shaded images](http://people.cs.umass.edu/~jcsu/papers/shape_recog/render_shaded_black_bg.blend)` and 
`[Blender script for rendering depth images](http://people.cs.umass.edu/~jcsu/papers/shape_recog/render_depth.blend)` point to the same file with different file name in commit ff476b2

**Comment by jongchyisu** [comment]
They are different in the way of rendering. You can see the difference in the "node editor".

**Comment by Luoyayu** [comment]
Thank you for your work,  I just focused on the code in Blender, they do function differently.
